#pragma once
#include <Arduino.h>

// Hardware layout
#define TFT_MOSI 23
#define TFT_MISO 19
#define TFT_SCLK 18
#define TFT_CS   15
#define TFT_DC   2
#define TFT_RST  4
#define TFT_LED  27

#define TOUCH_CLK  14
#define TOUCH_MOSI 13
#define TOUCH_MISO 12
#define TOUCH_CS    5
#define TOUCH_IRQ  21

#define BTN_PREV   32
#define BTN_NEXT   33
#define BTN_SELECT 25
#define BTN_BACK   26

#define TFT_WIDTH  320
#define TFT_HEIGHT 240
#define UI_HEADER_H 31
#define UI_FOOTER_Y 211
#define UI_FOOTER_H 29
#define UI_TEXT_FONT 2
#define UI_MAX_LINES 8

#define WIFI_SCAN_MAX 64
#define BLE_TARGET_LEN 18

#define DEFAULT_WIFI_SCAN_MS 5000
#define DEFAULT_BLE_SCAN_MS 5000
#define DEFAULT_DIAG_TIMEOUT_MS 1500
#define DEFAULT_DIAG_PINGS 3
#define DEFAULT_BRIGHTNESS 220
#define DEFAULT_WIFI_CHANNEL 1
#define DEFAULT_TOUCH_MIN_X 200
#define DEFAULT_TOUCH_MAX_X 3900
#define DEFAULT_TOUCH_MIN_Y 200
#define DEFAULT_TOUCH_MAX_Y 3900

#define SETTINGS_NAMESPACE "wt9"
#define SETTINGS_VERSION 2

enum AppState {
  ST_HOME,
  ST_WIFI_SCAN,
  ST_WIFI_SIGNAL,
  ST_WIFI_CHANNELS,
  ST_WIFI_SPECTRUM,
  ST_WIFI_HIDDEN,
  ST_WIFI_DETAIL,
  ST_WIFI_OPTIMIZER,
  ST_WIFI_DIAGNOSTIC,
  ST_WIFI_CAPTIVE,
  ST_WIFI_PACKETS,
  ST_WIFI_DEAUTH,
  ST_BLE_SCAN,
  ST_BLE_BEACONS,
  ST_BLE_GATT,
  ST_BLE_PROXIMITY,
  ST_BLE_ADVERTISER,
  ST_SECURITY_PASSWORD,
  ST_SYSTEM,
  ST_SETTINGS,
  ST_ABOUT
};
