[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32@6.7.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.flash_size = 4MB
board_build.partitions = huge_app.csv
board_build.flash_mode = qio
board_build.f_flash = 80000000L
lib_deps =
  bodmer/TFT_eSPI @ 2.5.43
  https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
build_flags =
  -DUSER_SETUP_LOADED
  -include User_Setup.h
