#!/usr/bin/env python3
from __future__ import annotations

import csv
import io
import sys
import urllib.request
from pathlib import Path

URL = "https://standards-oui.ieee.org/oui/oui.csv"
OUT = Path(__file__).resolve().parents[1] / "oui_db.h"
MAX_ENTRIES = 4000


def normalize_prefix(value: str) -> str:
    return value.replace("-", "").replace(":", "").strip().upper()[:6]


def main() -> int:
    print(f"Baixando OUI: {URL}")
    with urllib.request.urlopen(URL, timeout=20) as response:
        raw = response.read().decode("utf-8-sig")

    rows = csv.DictReader(io.StringIO(raw))
    entries: list[tuple[str, str]] = []
    seen: set[str] = set()

    for row in rows:
        prefix = normalize_prefix(row.get("Assignment", ""))
        org = (row.get("Organization Name") or "").strip()
        if len(prefix) != 6 or not all(c in "0123456789ABCDEF" for c in prefix) or not org:
            continue
        if prefix in seen:
            continue
        seen.add(prefix)
        entries.append((prefix, " ".join(org.split())))
        if len(entries) >= MAX_ENTRIES:
            break

    lines = [
        "#pragma once",
        "#include <Arduino.h>",
        "",
        "struct OuiEntry { uint32_t prefix; const char* name; };",
        "",
        "// Generated by tools/update_oui.py from the IEEE public OUI registry.",
        "// Regenerate periodically when a fresher database is required.",
        "static const OuiEntry OUI_DB[] = {",
    ]

    for prefix, org in entries:
        safe = org.replace('\\', '\\\\').replace('"', '\\"')
        lines.append(f'  {{0x{prefix}, "{safe}"}},')

    lines += [
        "};",
        "",
        "static String ouiVendor(const String& bssid) {",
        "  uint32_t prefix = 0;",
        "  uint8_t digits = 0;",
        "  for (size_t i = 0; i < bssid.length() && digits < 6; ++i) {",
        "    const char c = bssid[i];",
        "    if (c == ':' || c == '-') continue;",
        "    uint8_t value;",
        "    if (c >= '0' && c <= '9') value = c - '0';",
        "    else if (c >= 'A' && c <= 'F') value = c - 'A' + 10;",
        "    else if (c >= 'a' && c <= 'f') value = c - 'a' + 10;",
        "    else return \"Unknown\";",
        "    prefix = (prefix << 4) | value;",
        "    ++digits;",
        "  }",
        "  if (digits != 6) return \"Unknown\";",
        "  for (size_t i = 0; i < sizeof(OUI_DB) / sizeof(OUI_DB[0]); ++i) {",
        "    if (prefix == OUI_DB[i].prefix) return String(OUI_DB[i].name);",
        "  }",
        "  return \"Unknown\";",
        "}",
        "",
    ]

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Gerados {len(entries)} registros em {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
